# Generated by Django 5.2.1 on 2025-06-03 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='genres',
        ),
        migrations.RemoveField(
            model_name='game',
            name='themes',
        ),
        migrations.RemoveField(
            model_name='game',
            name='platforms',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.DeleteModel(
            name='Theme',
        ),
    ]
