# Generated by Django 5.2.1 on 2025-06-04 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_remove_game_genres_remove_game_themes_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Platform',
        ),
    ]
