# Generated by Django 5.2.1 on 2025-05-13 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_genre_theme_remove_game_publisher_game_cover_art_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='genre',
            field=models.ManyToManyField(blank=True, to='game.genre'),
        ),
        migrations.AlterField(
            model_name='game',
            name='themes',
            field=models.ManyToManyField(blank=True, to='game.theme'),
        ),
    ]
