# Generated by Django 5.2.1 on 2025-05-13 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_game_genre_alter_game_themes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='name',
            new_name='type',
        ),
        migrations.AlterField(
            model_name='game',
            name='genre',
            field=models.ManyToManyField(to='game.genre'),
        ),
        migrations.AlterField(
            model_name='game',
            name='themes',
            field=models.ManyToManyField(to='game.theme'),
        ),
    ]
