# Generated by Django 5.2.1 on 2025-06-04 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_delete_platform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='cover_art',
        ),
        migrations.RemoveField(
            model_name='game',
            name='title',
        ),
        migrations.RemoveField(
            model_name='game',
            name='url',
        ),
    ]
