# Generated by Django 5.2.1 on 2025-05-13 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_rename_name_genre_type_alter_game_genre_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='genre',
            new_name='genres',
        ),
    ]
