# Generated by Django 5.2.1 on 2025-05-13 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_rename_genre_game_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
