# Generated by Django 5.2.1 on 2025-06-01 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0001_initial'),
        ('patron', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('rating', models.FloatField(null=True)),
                ('completed_date', models.DateField()),
                ('completion_status', models.BooleanField()),
                ('hours', models.IntegerField(null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='game.game')),
                ('patron', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patron.patron')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='game.platform')),
            ],
        ),
    ]
