# Generated by Django 5.2.1 on 2025-05-18 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaryentry',
            name='hours',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='diaryentry',
            name='rating',
            field=models.FloatField(null=True),
        ),
    ]
