<<<<<<< HEAD
# Generated by Django 5.2.1 on 2025-11-19 02:31
=======
# Generated by Django 5.2.1 on 2025-06-01 22:04
>>>>>>> 5979d46 (update Game model to use game_id as primary key so that can use pk in a diary many to many relationship to query info on games rather than store in the Game or DiaryEntry models)

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fav_platform', models.CharField(max_length=25)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wishlist', models.ManyToManyField(to='game.game')),
            ],
        ),
    ]
